# Generated by Django 4.1.7 on 2023-02-26 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=16)),
                ('sentence', models.CharField(max_length=1024)),
                ('time', models.DateTimeField()),
                ('color', models.CharField(max_length=32)),
                ('pos', models.FloatField()),
                ('neg', models.FloatField()),
                ('neu', models.FloatField()),
                ('com', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=16, unique=True)),
            ],
            options={
                'permissions': (),
            },
        ),
    ]
